#-------------------------------------------------------------------------------
#
#    QuestaSim Configuration Tool
#
#    Author: Harry E. Zhurov
#
#-------------------------------------------------------------------------------

import os

import SCons.Builder
import SCons.Scanner

from utils import *

#-------------------------------------------------------------------------------
#
#    External Environment
#
MENTOR  = os.environ['MENTOR']
QUESTA  = os.path.join(MENTOR, 'questa', 'questasim', 'bin')

#-------------------------------------------------------------------------------
#
#    Action functions
#
def ipsim_script(target, source, env):

    cfg  = env['CFG']
    ext  = env['EXT']
    dirs = env['DIRS']

    src = source[0]
    trg = target[0]

    src_path = str(src)
    trg_path = str(trg)
    
    ip_name = drop_suffix(src.name)
    
    print('generate script:   \'' + trg.name + '\'')

    param_sect = 'config'
    ip_cfg     = read_ip_config(src_path, param_sect, env['CFG_PATH'])
    
    param_sect  = 'sources'
    search_root = env['IPSIM_CONFIG_PATH']
    src_sim     =  read_ipsim_config(ip_cfg['type'] + '.' + ext.CONFIG, search_root)
    
    src_str = ' '.join(src_sim).replace('${ip_name}', ip_name)
    
    title_text =\
    'IP core "' + ip_name + '" simulation library compile script' + os.linesep * 2 + \
    'This file is automatically generated. Do not edit the file manually.'
    
    text  = 'vlog -work ipsimlib' + env['VLOG_FLAGS'] + env['VLOG_OPTIMIZATION'] + ' \\' + os.linesep
    for i in src_sim:
        text += ' '*4 + i.replace('${ip_name}', ip_name) + ' \\' + os.linesep
    
    out = generate_title(title_text, '#')
    out += text
    out += generate_footer('#')
        
    with open(trg_path, 'w') as ofile:
        ofile.write(out)

    return None


#-------------------------------------------------------------------------------
#
#    Scanners
#
#---------------------------------------------------------------------
#
#    Scanner functions
#

#-------------------------------------------------------------------------------
#
#    Targets
#
def make_trg_nodes(src, src_suffix, trg_suffix, trg_dir, builder):

    s0 = src
    if(type(s0)) != str:
        s0 = str(s0[0])

    src_name = os.path.split(s0)[1]
    trg_name = src_name.replace(src_suffix, trg_suffix)
    trg      = os.path.join(trg_dir, trg_name)
    trg_list = builder(trg, src)

    #Depends(trg_list, 'top.scons')
    return trg_list

#---------------------------------------------------------------------
#
#    Pseudo-builders: IP simulation library stuff
#
def ipsim_scripts(env, src):
    ext     = env['EXT']
    dirs    = env['DIRS']
    res     = []
    src_sfx = '.'+ext.IP_CONFIG
    trg_sfx = '-ipsim.'+ext.SIM_SCRIPT
    trg_dir = dirs.IPSIM_SCRIPT
    builder = env.IpSimScript
    for i in src:
        ip_src = os.path.join(dirs.CFG_IP, i + '.' + ext.IP_CONFIG)
        res.append(make_trg_nodes(ip_src, src_sfx, trg_sfx, trg_dir, builder))    

    return res

#-------------------------------------------------------------------------------
#
#    Set up tool construction environment
#
def generate(env):
    
    ext = env['EXT']
    
    Scanner = SCons.Scanner.Scanner
    Builder = SCons.Builder.Builder
    
    env['VLOGCOM'] = os.path.join(QUESTA, 'vlog')
    env['VLIBCOM'] = os.path.join(QUESTA, 'vlib')
    env['VMAPCOM'] = os.path.join(QUESTA, 'vmap')
    env['SIMCOM']  = os.path.join(QUESTA, 'vsim') + ' -c'
    env['SIMGUI']  = os.path.join(MENTOR, 'questa', 'questa.sh') + ' -gui'
    
    env['VLOG_FLAGS']        = ' -incr -sv -mfcu'
    env['VLOG_OPTIMIZATION'] = ' -O5'
    if 'vivado' in env['TOOLS']:
        env['VOPT_FLAGS']        = ' glbl'
    

    env['VERBOSE'] = True
    
    env['IPSIM_CONFIG_PATH'] = os.path.join(str(env.Dir('#')), 'lib', 'ipsim')
    
    #-----------------------------------------------------------------
    #
    #   Scanners
    #
#   CfgImportScanner = Scanner(name          = 'CfgImportScanner',
#                      function      = scan_cfg_files,
#                      skeys         = ['.' + ext.IP_CONFIG],
#                      recursive     = True,
#                      path_function = SCons.Scanner.FindPathDirs('SETTINGS_SEARCH_PATH')
#                     )

    #-----------------------------------------------------------------
    #
    #   Builders
    #
    IpSimScript = Builder(action = ipsim_script,
                          suffix = ext.TOOL_SCRIPT)
        
    
    Builders = {
        'IpSimScript' : IpSimScript
    }
    
    
    env.Append(BUILDERS = Builders)

    #-----------------------------------------------------------------
    #
    #   IP core processing pseudo-builders
    #
    env.AddMethod(ipsim_scripts, 'IpSimScripts')
        
#-------------------------------------------------------------------------------
def exists(env):
    print('questa tool: exists')
#-------------------------------------------------------------------------------
    
