
import : clk dpc board

parameters:
    WIDTH          : 4                      
    LENGTH         : 2000
    LENGTH_WIDTH   : = clog2(LENGTH) 
    LINK_WIDTH     : '4'
    LINK_SPEED     : '5.0'
    SLON           : = WIDTH + LENGTH_WIDTH
    CLK_PERIOD     : = 1e3/clk.MAIN_CLK_FREQ      # ns
    TASK_COUNT     : = dpc.TASK_QUEUE_COUNT
    TASK_POOL_SIZE : = dpc.TASK_DATA_LEN*SLON
    TIME_SLOT      : = int(dpc.TIME_SLOT/WIDTH)
    MAMONT         : = os.path.join('slon', 'mamont')
    ADDR           : 0x1000

